name: Acceptance Tests

on:
  push:
    branches:
      - main

jobs:
  download-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Downlaod Liquid Repository
      run: |
        git clone https://github.com/shrihari-prakash/liquid.git
