name: Acceptance Tests

on:
  push:
    branches:
      - main

jobs:
  download-repo:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Download Liquid Repository
      run: |
        git clone https://github.com/shrihari-prakash/liquid.git
        echo "Current Working Directory: $PWD"
        ls -l
        cd liquid/quickstart
        docker compose pull
        docker compose up -d
        docker ps -a
        cd ..
        npm install
        cd scripts
        ls -l
        node create-application-client.js mongodbConenctionString=mongodb://liquid_mongodb:27017/liquid clientSecret=Liquid redirectUrls=http://localhost:2000/health
        
