name: Acceptance Tests

on:
  push:
    branches:
      - main

jobs:
  download-repo:
    runs-on: ubuntu-latest
    defaults:
     run:
       working-directory: ./app
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Download Liquid Repository
      run: |
        git clone https://github.com/shrihari-prakash/liquid.git
        cd ./liquid/quickstart
        docker-compose pull
        docker-compose up
