name: Acceptance Tests

on:
  workflow_dispatch:
  #push:
    #branches:
     # - main

jobs:
  download-repo:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Download Liquid Repository
      run: |
        git clone https://github.com/shrihari-prakash/liquid.git
        echo "Current Working Directory: $PWD"
        ls -l
        cd liquid/quickstart
        docker compose pull
        docker compose up -d
        docker ps -a
        cd ..
    - name: Run Test
      run: |
        cd liquid
        npm install
        ls -l
        node ./scripts/create-application-client.js mongodbConenctionString=mongodb://localhost:27017/liquid clientSecret=Liquid redirectUrls=http://localhost:2000/health
        cd ..
        npm install
        npm test
    - name: Send Email
      run: |
        node ./mailer.js
        env:
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
    - name: Output the result
      uses: actions/upload-artifact@v3
      with:
          name: Reports
          path: ./features/reports
        
